namespace app
{
    partial class main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(main));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuColorTransition1 = new Bunifu.UI.WinForms.BunifuColorTransition(this.components);
            this.PnlTop = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnExit = new System.Windows.Forms.Button();
            this.lblTitle2 = new System.Windows.Forms.Label();
            this.PnlFormLoader = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.buttonAbout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonCRM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonHR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonFR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonInv = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonTables = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonOrders = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonMenu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PnlImage = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuPnel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.lblTitle1 = new System.Windows.Forms.Label();
            this.PnlTop.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.PnlImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuColorTransition1
            // 
            this.bunifuColorTransition1.AutoTransition = false;
            this.bunifuColorTransition1.ColorArray = new System.Drawing.Color[] {
        System.Drawing.Color.Purple,
        System.Drawing.Color.LightBlue,
        System.Drawing.Color.Orange};
            this.bunifuColorTransition1.EndColor = System.Drawing.Color.White;
            this.bunifuColorTransition1.Interval = 10;
            this.bunifuColorTransition1.ProgessValue = 0;
            this.bunifuColorTransition1.StartColor = System.Drawing.Color.White;
            this.bunifuColorTransition1.TransitionControl = null;
            // 
            // PnlTop
            // 
            this.PnlTop.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.PnlTop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PnlTop.BackgroundImage")));
            this.PnlTop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PnlTop.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.PnlTop.BorderRadius = 3;
            this.PnlTop.BorderThickness = 1;
            this.PnlTop.Controls.Add(this.btnExit);
            this.PnlTop.Controls.Add(this.lblTitle2);
            this.PnlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.PnlTop.Location = new System.Drawing.Point(200, 0);
            this.PnlTop.Name = "PnlTop";
            this.PnlTop.ShowBorders = true;
            this.PnlTop.Size = new System.Drawing.Size(1081, 110);
            this.PnlTop.TabIndex = 4;
            // 
            // btnExit
            // 
            this.btnExit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExit.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExit.Location = new System.Drawing.Point(1014, 12);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(53, 35);
            this.btnExit.TabIndex = 29;
            this.btnExit.Text = "X";
            this.btnExit.UseVisualStyleBackColor = false;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // lblTitle2
            // 
            this.lblTitle2.AutoSize = true;
            this.lblTitle2.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle2.Font = new System.Drawing.Font("Nirmala UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle2.ForeColor = System.Drawing.Color.White;
            this.lblTitle2.Location = new System.Drawing.Point(38, 39);
            this.lblTitle2.Name = "lblTitle2";
            this.lblTitle2.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblTitle2.Size = new System.Drawing.Size(107, 41);
            this.lblTitle2.TabIndex = 28;
            this.lblTitle2.Text = "Home";
            // 
            // PnlFormLoader
            // 
            this.PnlFormLoader.BackgroundColor = System.Drawing.Color.White;
            this.PnlFormLoader.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PnlFormLoader.BackgroundImage")));
            this.PnlFormLoader.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PnlFormLoader.BorderColor = System.Drawing.Color.Transparent;
            this.PnlFormLoader.BorderRadius = 3;
            this.PnlFormLoader.BorderThickness = 1;
            this.PnlFormLoader.Location = new System.Drawing.Point(200, 107);
            this.PnlFormLoader.Name = "PnlFormLoader";
            this.PnlFormLoader.ShowBorders = true;
            this.PnlFormLoader.Size = new System.Drawing.Size(1081, 570);
            this.PnlFormLoader.TabIndex = 3;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.buttonAbout);
            this.bunifuPanel1.Controls.Add(this.buttonCRM);
            this.bunifuPanel1.Controls.Add(this.buttonHR);
            this.bunifuPanel1.Controls.Add(this.buttonFR);
            this.bunifuPanel1.Controls.Add(this.buttonInv);
            this.bunifuPanel1.Controls.Add(this.buttonCS);
            this.bunifuPanel1.Controls.Add(this.buttonTables);
            this.bunifuPanel1.Controls.Add(this.buttonOrders);
            this.bunifuPanel1.Controls.Add(this.buttonMenu);
            this.bunifuPanel1.Controls.Add(this.buttonHome);
            this.bunifuPanel1.Controls.Add(this.PnlImage);
            this.bunifuPanel1.Controls.Add(this.bunifuPnel3);
            this.bunifuPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuPanel1.Controls.Add(this.lblTitle1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(200, 650);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // buttonAbout
            // 
            this.buttonAbout.AllowAnimations = true;
            this.buttonAbout.AllowMouseEffects = true;
            this.buttonAbout.AllowToggling = false;
            this.buttonAbout.AnimationSpeed = 200;
            this.buttonAbout.AutoGenerateColors = false;
            this.buttonAbout.AutoRoundBorders = false;
            this.buttonAbout.AutoSizeLeftIcon = true;
            this.buttonAbout.AutoSizeRightIcon = true;
            this.buttonAbout.BackColor = System.Drawing.Color.Transparent;
            this.buttonAbout.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonAbout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonAbout.BackgroundImage")));
            this.buttonAbout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAbout.ButtonText = "About Us";
            this.buttonAbout.ButtonTextMarginLeft = 0;
            this.buttonAbout.ColorContrastOnClick = 45;
            this.buttonAbout.ColorContrastOnHover = 45;
            this.buttonAbout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonAbout.CustomizableEdges = borderEdges1;
            this.buttonAbout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonAbout.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.buttonAbout.DisabledFillColor = System.Drawing.Color.Transparent;
            this.buttonAbout.DisabledForecolor = System.Drawing.Color.Red;
            this.buttonAbout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonAbout.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonAbout.ForeColor = System.Drawing.Color.Silver;
            this.buttonAbout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonAbout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonAbout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonAbout.IconMarginLeft = 11;
            this.buttonAbout.IconPadding = 10;
            this.buttonAbout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonAbout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonAbout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonAbout.IconSize = 25;
            this.buttonAbout.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonAbout.IdleBorderRadius = 1;
            this.buttonAbout.IdleBorderThickness = 1;
            this.buttonAbout.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonAbout.IdleIconLeftImage = null;
            this.buttonAbout.IdleIconRightImage = null;
            this.buttonAbout.IndicateFocus = false;
            this.buttonAbout.Location = new System.Drawing.Point(27, 611);
            this.buttonAbout.Name = "buttonAbout";
            this.buttonAbout.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonAbout.OnDisabledState.BorderRadius = 1;
            this.buttonAbout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAbout.OnDisabledState.BorderThickness = 1;
            this.buttonAbout.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.buttonAbout.OnDisabledState.ForeColor = System.Drawing.Color.Red;
            this.buttonAbout.OnDisabledState.IconLeftImage = null;
            this.buttonAbout.OnDisabledState.IconRightImage = null;
            this.buttonAbout.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonAbout.onHoverState.BorderRadius = 1;
            this.buttonAbout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAbout.onHoverState.BorderThickness = 1;
            this.buttonAbout.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.buttonAbout.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.buttonAbout.onHoverState.IconLeftImage = null;
            this.buttonAbout.onHoverState.IconRightImage = null;
            this.buttonAbout.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonAbout.OnIdleState.BorderRadius = 1;
            this.buttonAbout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAbout.OnIdleState.BorderThickness = 1;
            this.buttonAbout.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonAbout.OnIdleState.ForeColor = System.Drawing.Color.Silver;
            this.buttonAbout.OnIdleState.IconLeftImage = null;
            this.buttonAbout.OnIdleState.IconRightImage = null;
            this.buttonAbout.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonAbout.OnPressedState.BorderRadius = 1;
            this.buttonAbout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAbout.OnPressedState.BorderThickness = 1;
            this.buttonAbout.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.buttonAbout.OnPressedState.ForeColor = System.Drawing.Color.Red;
            this.buttonAbout.OnPressedState.IconLeftImage = null;
            this.buttonAbout.OnPressedState.IconRightImage = null;
            this.buttonAbout.Size = new System.Drawing.Size(150, 39);
            this.buttonAbout.TabIndex = 19;
            this.buttonAbout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonAbout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonAbout.TextMarginLeft = 0;
            this.buttonAbout.TextPadding = new System.Windows.Forms.Padding(0, 7, 0, 0);
            this.buttonAbout.UseDefaultRadiusAndThickness = true;
            this.buttonAbout.Click += new System.EventHandler(this.buttonAbout_Click_1);
            // 
            // buttonCRM
            // 
            this.buttonCRM.AllowAnimations = true;
            this.buttonCRM.AllowMouseEffects = true;
            this.buttonCRM.AllowToggling = false;
            this.buttonCRM.AnimationSpeed = 200;
            this.buttonCRM.AutoGenerateColors = false;
            this.buttonCRM.AutoRoundBorders = false;
            this.buttonCRM.AutoSizeLeftIcon = true;
            this.buttonCRM.AutoSizeRightIcon = true;
            this.buttonCRM.BackColor = System.Drawing.Color.Transparent;
            this.buttonCRM.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonCRM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonCRM.BackgroundImage")));
            this.buttonCRM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCRM.ButtonText = "CRM";
            this.buttonCRM.ButtonTextMarginLeft = 0;
            this.buttonCRM.ColorContrastOnClick = 45;
            this.buttonCRM.ColorContrastOnHover = 45;
            this.buttonCRM.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonCRM.CustomizableEdges = borderEdges2;
            this.buttonCRM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonCRM.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonCRM.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonCRM.DisabledForecolor = System.Drawing.Color.White;
            this.buttonCRM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonCRM.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonCRM.ForeColor = System.Drawing.Color.White;
            this.buttonCRM.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonCRM.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonCRM.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonCRM.IconMarginLeft = 11;
            this.buttonCRM.IconPadding = 10;
            this.buttonCRM.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonCRM.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonCRM.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonCRM.IconSize = 25;
            this.buttonCRM.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonCRM.IdleBorderRadius = 35;
            this.buttonCRM.IdleBorderThickness = 1;
            this.buttonCRM.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonCRM.IdleIconLeftImage = null;
            this.buttonCRM.IdleIconRightImage = null;
            this.buttonCRM.IndicateFocus = false;
            this.buttonCRM.Location = new System.Drawing.Point(-41, 217);
            this.buttonCRM.Name = "buttonCRM";
            this.buttonCRM.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonCRM.OnDisabledState.BorderRadius = 35;
            this.buttonCRM.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCRM.OnDisabledState.BorderThickness = 1;
            this.buttonCRM.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonCRM.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.buttonCRM.OnDisabledState.IconLeftImage = null;
            this.buttonCRM.OnDisabledState.IconRightImage = null;
            this.buttonCRM.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonCRM.onHoverState.BorderRadius = 35;
            this.buttonCRM.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCRM.onHoverState.BorderThickness = 1;
            this.buttonCRM.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonCRM.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonCRM.onHoverState.IconLeftImage = null;
            this.buttonCRM.onHoverState.IconRightImage = null;
            this.buttonCRM.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonCRM.OnIdleState.BorderRadius = 35;
            this.buttonCRM.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCRM.OnIdleState.BorderThickness = 1;
            this.buttonCRM.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonCRM.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonCRM.OnIdleState.IconLeftImage = null;
            this.buttonCRM.OnIdleState.IconRightImage = null;
            this.buttonCRM.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonCRM.OnPressedState.BorderRadius = 35;
            this.buttonCRM.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCRM.OnPressedState.BorderThickness = 1;
            this.buttonCRM.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonCRM.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonCRM.OnPressedState.IconLeftImage = null;
            this.buttonCRM.OnPressedState.IconRightImage = null;
            this.buttonCRM.Size = new System.Drawing.Size(164, 39);
            this.buttonCRM.TabIndex = 18;
            this.buttonCRM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonCRM.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonCRM.TextMarginLeft = 0;
            this.buttonCRM.TextPadding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.buttonCRM.UseDefaultRadiusAndThickness = true;
            this.buttonCRM.Click += new System.EventHandler(this.buttonCRM_Click_1);
            // 
            // buttonHR
            // 
            this.buttonHR.AllowAnimations = true;
            this.buttonHR.AllowMouseEffects = true;
            this.buttonHR.AllowToggling = false;
            this.buttonHR.AnimationSpeed = 200;
            this.buttonHR.AutoGenerateColors = false;
            this.buttonHR.AutoRoundBorders = false;
            this.buttonHR.AutoSizeLeftIcon = true;
            this.buttonHR.AutoSizeRightIcon = true;
            this.buttonHR.BackColor = System.Drawing.Color.Transparent;
            this.buttonHR.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonHR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonHR.BackgroundImage")));
            this.buttonHR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHR.ButtonText = "Human Resource";
            this.buttonHR.ButtonTextMarginLeft = 0;
            this.buttonHR.ColorContrastOnClick = 45;
            this.buttonHR.ColorContrastOnHover = 45;
            this.buttonHR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.buttonHR.CustomizableEdges = borderEdges3;
            this.buttonHR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonHR.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonHR.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonHR.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonHR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonHR.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.buttonHR.ForeColor = System.Drawing.Color.White;
            this.buttonHR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonHR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonHR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonHR.IconMarginLeft = 11;
            this.buttonHR.IconPadding = 10;
            this.buttonHR.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonHR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonHR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonHR.IconSize = 25;
            this.buttonHR.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonHR.IdleBorderRadius = 35;
            this.buttonHR.IdleBorderThickness = 1;
            this.buttonHR.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonHR.IdleIconLeftImage = null;
            this.buttonHR.IdleIconRightImage = null;
            this.buttonHR.IndicateFocus = false;
            this.buttonHR.Location = new System.Drawing.Point(-28, 532);
            this.buttonHR.Name = "buttonHR";
            this.buttonHR.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonHR.OnDisabledState.BorderRadius = 35;
            this.buttonHR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHR.OnDisabledState.BorderThickness = 1;
            this.buttonHR.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonHR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonHR.OnDisabledState.IconLeftImage = null;
            this.buttonHR.OnDisabledState.IconRightImage = null;
            this.buttonHR.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonHR.onHoverState.BorderRadius = 35;
            this.buttonHR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHR.onHoverState.BorderThickness = 1;
            this.buttonHR.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonHR.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonHR.onHoverState.IconLeftImage = null;
            this.buttonHR.onHoverState.IconRightImage = null;
            this.buttonHR.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonHR.OnIdleState.BorderRadius = 35;
            this.buttonHR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHR.OnIdleState.BorderThickness = 1;
            this.buttonHR.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonHR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonHR.OnIdleState.IconLeftImage = null;
            this.buttonHR.OnIdleState.IconRightImage = null;
            this.buttonHR.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonHR.OnPressedState.BorderRadius = 35;
            this.buttonHR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHR.OnPressedState.BorderThickness = 1;
            this.buttonHR.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonHR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonHR.OnPressedState.IconLeftImage = null;
            this.buttonHR.OnPressedState.IconRightImage = null;
            this.buttonHR.Size = new System.Drawing.Size(227, 39);
            this.buttonHR.TabIndex = 17;
            this.buttonHR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonHR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonHR.TextMarginLeft = 0;
            this.buttonHR.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.buttonHR.UseDefaultRadiusAndThickness = true;
            this.buttonHR.Click += new System.EventHandler(this.buttonHR_Click_1);
            // 
            // buttonFR
            // 
            this.buttonFR.AllowAnimations = true;
            this.buttonFR.AllowMouseEffects = true;
            this.buttonFR.AllowToggling = false;
            this.buttonFR.AnimationSpeed = 200;
            this.buttonFR.AutoGenerateColors = false;
            this.buttonFR.AutoRoundBorders = false;
            this.buttonFR.AutoSizeLeftIcon = true;
            this.buttonFR.AutoSizeRightIcon = true;
            this.buttonFR.BackColor = System.Drawing.Color.Transparent;
            this.buttonFR.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonFR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonFR.BackgroundImage")));
            this.buttonFR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonFR.ButtonText = "Financial Records";
            this.buttonFR.ButtonTextMarginLeft = 0;
            this.buttonFR.ColorContrastOnClick = 45;
            this.buttonFR.ColorContrastOnHover = 45;
            this.buttonFR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.buttonFR.CustomizableEdges = borderEdges4;
            this.buttonFR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonFR.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonFR.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonFR.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonFR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonFR.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.buttonFR.ForeColor = System.Drawing.Color.White;
            this.buttonFR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonFR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonFR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonFR.IconMarginLeft = 11;
            this.buttonFR.IconPadding = 10;
            this.buttonFR.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonFR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonFR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonFR.IconSize = 25;
            this.buttonFR.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonFR.IdleBorderRadius = 35;
            this.buttonFR.IdleBorderThickness = 1;
            this.buttonFR.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonFR.IdleIconLeftImage = null;
            this.buttonFR.IdleIconRightImage = null;
            this.buttonFR.IndicateFocus = false;
            this.buttonFR.Location = new System.Drawing.Point(-28, 487);
            this.buttonFR.Name = "buttonFR";
            this.buttonFR.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonFR.OnDisabledState.BorderRadius = 35;
            this.buttonFR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonFR.OnDisabledState.BorderThickness = 1;
            this.buttonFR.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonFR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonFR.OnDisabledState.IconLeftImage = null;
            this.buttonFR.OnDisabledState.IconRightImage = null;
            this.buttonFR.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonFR.onHoverState.BorderRadius = 35;
            this.buttonFR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonFR.onHoverState.BorderThickness = 1;
            this.buttonFR.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonFR.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonFR.onHoverState.IconLeftImage = null;
            this.buttonFR.onHoverState.IconRightImage = null;
            this.buttonFR.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonFR.OnIdleState.BorderRadius = 35;
            this.buttonFR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonFR.OnIdleState.BorderThickness = 1;
            this.buttonFR.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonFR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonFR.OnIdleState.IconLeftImage = null;
            this.buttonFR.OnIdleState.IconRightImage = null;
            this.buttonFR.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonFR.OnPressedState.BorderRadius = 35;
            this.buttonFR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonFR.OnPressedState.BorderThickness = 1;
            this.buttonFR.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonFR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonFR.OnPressedState.IconLeftImage = null;
            this.buttonFR.OnPressedState.IconRightImage = null;
            this.buttonFR.Size = new System.Drawing.Size(227, 39);
            this.buttonFR.TabIndex = 16;
            this.buttonFR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonFR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonFR.TextMarginLeft = 0;
            this.buttonFR.TextPadding = new System.Windows.Forms.Padding(10, 0, -10, 0);
            this.buttonFR.UseDefaultRadiusAndThickness = true;
            this.buttonFR.Click += new System.EventHandler(this.buttonFR_Click_1);
            // 
            // buttonInv
            // 
            this.buttonInv.AllowAnimations = true;
            this.buttonInv.AllowMouseEffects = true;
            this.buttonInv.AllowToggling = false;
            this.buttonInv.AnimationSpeed = 200;
            this.buttonInv.AutoGenerateColors = false;
            this.buttonInv.AutoRoundBorders = false;
            this.buttonInv.AutoSizeLeftIcon = true;
            this.buttonInv.AutoSizeRightIcon = true;
            this.buttonInv.BackColor = System.Drawing.Color.Transparent;
            this.buttonInv.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonInv.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonInv.BackgroundImage")));
            this.buttonInv.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInv.ButtonText = "Inventory";
            this.buttonInv.ButtonTextMarginLeft = 0;
            this.buttonInv.ColorContrastOnClick = 45;
            this.buttonInv.ColorContrastOnHover = 45;
            this.buttonInv.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.buttonInv.CustomizableEdges = borderEdges5;
            this.buttonInv.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonInv.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonInv.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonInv.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonInv.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonInv.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonInv.ForeColor = System.Drawing.Color.White;
            this.buttonInv.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonInv.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonInv.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonInv.IconMarginLeft = 11;
            this.buttonInv.IconPadding = 10;
            this.buttonInv.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonInv.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonInv.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonInv.IconSize = 25;
            this.buttonInv.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonInv.IdleBorderRadius = 35;
            this.buttonInv.IdleBorderThickness = 1;
            this.buttonInv.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonInv.IdleIconLeftImage = null;
            this.buttonInv.IdleIconRightImage = null;
            this.buttonInv.IndicateFocus = false;
            this.buttonInv.Location = new System.Drawing.Point(-50, 397);
            this.buttonInv.Name = "buttonInv";
            this.buttonInv.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonInv.OnDisabledState.BorderRadius = 35;
            this.buttonInv.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInv.OnDisabledState.BorderThickness = 1;
            this.buttonInv.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonInv.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonInv.OnDisabledState.IconLeftImage = null;
            this.buttonInv.OnDisabledState.IconRightImage = null;
            this.buttonInv.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonInv.onHoverState.BorderRadius = 35;
            this.buttonInv.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInv.onHoverState.BorderThickness = 1;
            this.buttonInv.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonInv.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonInv.onHoverState.IconLeftImage = null;
            this.buttonInv.onHoverState.IconRightImage = null;
            this.buttonInv.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonInv.OnIdleState.BorderRadius = 35;
            this.buttonInv.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInv.OnIdleState.BorderThickness = 1;
            this.buttonInv.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonInv.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonInv.OnIdleState.IconLeftImage = null;
            this.buttonInv.OnIdleState.IconRightImage = null;
            this.buttonInv.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonInv.OnPressedState.BorderRadius = 35;
            this.buttonInv.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInv.OnPressedState.BorderThickness = 1;
            this.buttonInv.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonInv.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonInv.OnPressedState.IconLeftImage = null;
            this.buttonInv.OnPressedState.IconRightImage = null;
            this.buttonInv.Size = new System.Drawing.Size(227, 39);
            this.buttonInv.TabIndex = 15;
            this.buttonInv.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonInv.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonInv.TextMarginLeft = 0;
            this.buttonInv.TextPadding = new System.Windows.Forms.Padding(4, 0, 0, 0);
            this.buttonInv.UseDefaultRadiusAndThickness = true;
            this.buttonInv.Click += new System.EventHandler(this.buttonInv_Click_1);
            // 
            // buttonCS
            // 
            this.buttonCS.AllowAnimations = true;
            this.buttonCS.AllowMouseEffects = true;
            this.buttonCS.AllowToggling = false;
            this.buttonCS.AnimationSpeed = 200;
            this.buttonCS.AutoGenerateColors = false;
            this.buttonCS.AutoRoundBorders = false;
            this.buttonCS.AutoSizeLeftIcon = true;
            this.buttonCS.AutoSizeRightIcon = true;
            this.buttonCS.BackColor = System.Drawing.Color.Transparent;
            this.buttonCS.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonCS.BackgroundImage")));
            this.buttonCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCS.ButtonText = "Cusine Suggestions";
            this.buttonCS.ButtonTextMarginLeft = 0;
            this.buttonCS.ColorContrastOnClick = 45;
            this.buttonCS.ColorContrastOnHover = 45;
            this.buttonCS.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.buttonCS.CustomizableEdges = borderEdges6;
            this.buttonCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonCS.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonCS.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.buttonCS.ForeColor = System.Drawing.Color.White;
            this.buttonCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonCS.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonCS.IconMarginLeft = 11;
            this.buttonCS.IconPadding = 10;
            this.buttonCS.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonCS.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonCS.IconSize = 25;
            this.buttonCS.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonCS.IdleBorderRadius = 35;
            this.buttonCS.IdleBorderThickness = 1;
            this.buttonCS.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonCS.IdleIconLeftImage = null;
            this.buttonCS.IdleIconRightImage = null;
            this.buttonCS.IndicateFocus = false;
            this.buttonCS.Location = new System.Drawing.Point(-41, 442);
            this.buttonCS.Name = "buttonCS";
            this.buttonCS.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonCS.OnDisabledState.BorderRadius = 35;
            this.buttonCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCS.OnDisabledState.BorderThickness = 1;
            this.buttonCS.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonCS.OnDisabledState.IconLeftImage = null;
            this.buttonCS.OnDisabledState.IconRightImage = null;
            this.buttonCS.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonCS.onHoverState.BorderRadius = 35;
            this.buttonCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCS.onHoverState.BorderThickness = 1;
            this.buttonCS.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonCS.onHoverState.IconLeftImage = null;
            this.buttonCS.onHoverState.IconRightImage = null;
            this.buttonCS.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonCS.OnIdleState.BorderRadius = 35;
            this.buttonCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCS.OnIdleState.BorderThickness = 1;
            this.buttonCS.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonCS.OnIdleState.IconLeftImage = null;
            this.buttonCS.OnIdleState.IconRightImage = null;
            this.buttonCS.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonCS.OnPressedState.BorderRadius = 35;
            this.buttonCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonCS.OnPressedState.BorderThickness = 1;
            this.buttonCS.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonCS.OnPressedState.IconLeftImage = null;
            this.buttonCS.OnPressedState.IconRightImage = null;
            this.buttonCS.Size = new System.Drawing.Size(240, 39);
            this.buttonCS.TabIndex = 14;
            this.buttonCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonCS.TextMarginLeft = 0;
            this.buttonCS.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.buttonCS.UseDefaultRadiusAndThickness = true;
            this.buttonCS.Click += new System.EventHandler(this.buttonCS_Click_1);
            // 
            // buttonTables
            // 
            this.buttonTables.AllowAnimations = true;
            this.buttonTables.AllowMouseEffects = true;
            this.buttonTables.AllowToggling = false;
            this.buttonTables.AnimationSpeed = 200;
            this.buttonTables.AutoGenerateColors = false;
            this.buttonTables.AutoRoundBorders = false;
            this.buttonTables.AutoSizeLeftIcon = true;
            this.buttonTables.AutoSizeRightIcon = true;
            this.buttonTables.BackColor = System.Drawing.Color.Transparent;
            this.buttonTables.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonTables.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonTables.BackgroundImage")));
            this.buttonTables.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonTables.ButtonText = "Tables";
            this.buttonTables.ButtonTextMarginLeft = 0;
            this.buttonTables.ColorContrastOnClick = 45;
            this.buttonTables.ColorContrastOnHover = 45;
            this.buttonTables.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.buttonTables.CustomizableEdges = borderEdges7;
            this.buttonTables.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonTables.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonTables.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonTables.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTables.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonTables.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonTables.ForeColor = System.Drawing.Color.White;
            this.buttonTables.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonTables.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonTables.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonTables.IconMarginLeft = 11;
            this.buttonTables.IconPadding = 10;
            this.buttonTables.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonTables.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonTables.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonTables.IconSize = 25;
            this.buttonTables.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonTables.IdleBorderRadius = 35;
            this.buttonTables.IdleBorderThickness = 1;
            this.buttonTables.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonTables.IdleIconLeftImage = null;
            this.buttonTables.IdleIconRightImage = null;
            this.buttonTables.IndicateFocus = false;
            this.buttonTables.Location = new System.Drawing.Point(-40, 352);
            this.buttonTables.Name = "buttonTables";
            this.buttonTables.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonTables.OnDisabledState.BorderRadius = 35;
            this.buttonTables.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonTables.OnDisabledState.BorderThickness = 1;
            this.buttonTables.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonTables.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonTables.OnDisabledState.IconLeftImage = null;
            this.buttonTables.OnDisabledState.IconRightImage = null;
            this.buttonTables.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonTables.onHoverState.BorderRadius = 35;
            this.buttonTables.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonTables.onHoverState.BorderThickness = 1;
            this.buttonTables.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonTables.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonTables.onHoverState.IconLeftImage = null;
            this.buttonTables.onHoverState.IconRightImage = null;
            this.buttonTables.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonTables.OnIdleState.BorderRadius = 35;
            this.buttonTables.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonTables.OnIdleState.BorderThickness = 1;
            this.buttonTables.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonTables.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonTables.OnIdleState.IconLeftImage = null;
            this.buttonTables.OnIdleState.IconRightImage = null;
            this.buttonTables.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonTables.OnPressedState.BorderRadius = 35;
            this.buttonTables.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonTables.OnPressedState.BorderThickness = 1;
            this.buttonTables.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonTables.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonTables.OnPressedState.IconLeftImage = null;
            this.buttonTables.OnPressedState.IconRightImage = null;
            this.buttonTables.Size = new System.Drawing.Size(163, 39);
            this.buttonTables.TabIndex = 13;
            this.buttonTables.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonTables.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonTables.TextMarginLeft = 0;
            this.buttonTables.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.buttonTables.UseDefaultRadiusAndThickness = true;
            this.buttonTables.Click += new System.EventHandler(this.buttonTables_Click_1);
            // 
            // buttonOrders
            // 
            this.buttonOrders.AllowAnimations = true;
            this.buttonOrders.AllowMouseEffects = true;
            this.buttonOrders.AllowToggling = false;
            this.buttonOrders.AnimationSpeed = 200;
            this.buttonOrders.AutoGenerateColors = false;
            this.buttonOrders.AutoRoundBorders = false;
            this.buttonOrders.AutoSizeLeftIcon = true;
            this.buttonOrders.AutoSizeRightIcon = true;
            this.buttonOrders.BackColor = System.Drawing.Color.Transparent;
            this.buttonOrders.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonOrders.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonOrders.BackgroundImage")));
            this.buttonOrders.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOrders.ButtonText = "Orders";
            this.buttonOrders.ButtonTextMarginLeft = 0;
            this.buttonOrders.ColorContrastOnClick = 45;
            this.buttonOrders.ColorContrastOnHover = 45;
            this.buttonOrders.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.buttonOrders.CustomizableEdges = borderEdges8;
            this.buttonOrders.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonOrders.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonOrders.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonOrders.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOrders.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonOrders.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonOrders.ForeColor = System.Drawing.Color.White;
            this.buttonOrders.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonOrders.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOrders.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonOrders.IconMarginLeft = 11;
            this.buttonOrders.IconPadding = 10;
            this.buttonOrders.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonOrders.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOrders.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonOrders.IconSize = 25;
            this.buttonOrders.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonOrders.IdleBorderRadius = 35;
            this.buttonOrders.IdleBorderThickness = 1;
            this.buttonOrders.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonOrders.IdleIconLeftImage = null;
            this.buttonOrders.IdleIconRightImage = null;
            this.buttonOrders.IndicateFocus = false;
            this.buttonOrders.Location = new System.Drawing.Point(-40, 307);
            this.buttonOrders.Name = "buttonOrders";
            this.buttonOrders.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonOrders.OnDisabledState.BorderRadius = 35;
            this.buttonOrders.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOrders.OnDisabledState.BorderThickness = 1;
            this.buttonOrders.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonOrders.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOrders.OnDisabledState.IconLeftImage = null;
            this.buttonOrders.OnDisabledState.IconRightImage = null;
            this.buttonOrders.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonOrders.onHoverState.BorderRadius = 35;
            this.buttonOrders.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOrders.onHoverState.BorderThickness = 1;
            this.buttonOrders.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonOrders.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonOrders.onHoverState.IconLeftImage = null;
            this.buttonOrders.onHoverState.IconRightImage = null;
            this.buttonOrders.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonOrders.OnIdleState.BorderRadius = 35;
            this.buttonOrders.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOrders.OnIdleState.BorderThickness = 1;
            this.buttonOrders.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonOrders.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonOrders.OnIdleState.IconLeftImage = null;
            this.buttonOrders.OnIdleState.IconRightImage = null;
            this.buttonOrders.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonOrders.OnPressedState.BorderRadius = 35;
            this.buttonOrders.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOrders.OnPressedState.BorderThickness = 1;
            this.buttonOrders.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonOrders.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonOrders.OnPressedState.IconLeftImage = null;
            this.buttonOrders.OnPressedState.IconRightImage = null;
            this.buttonOrders.Size = new System.Drawing.Size(163, 39);
            this.buttonOrders.TabIndex = 12;
            this.buttonOrders.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonOrders.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonOrders.TextMarginLeft = 0;
            this.buttonOrders.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.buttonOrders.UseDefaultRadiusAndThickness = true;
            this.buttonOrders.Click += new System.EventHandler(this.buttonOrders_Click_1);
            // 
            // buttonMenu
            // 
            this.buttonMenu.AllowAnimations = true;
            this.buttonMenu.AllowMouseEffects = true;
            this.buttonMenu.AllowToggling = false;
            this.buttonMenu.AnimationSpeed = 200;
            this.buttonMenu.AutoGenerateColors = false;
            this.buttonMenu.AutoRoundBorders = false;
            this.buttonMenu.AutoSizeLeftIcon = true;
            this.buttonMenu.AutoSizeRightIcon = true;
            this.buttonMenu.BackColor = System.Drawing.Color.Transparent;
            this.buttonMenu.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonMenu.BackgroundImage")));
            this.buttonMenu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonMenu.ButtonText = "Menu";
            this.buttonMenu.ButtonTextMarginLeft = 0;
            this.buttonMenu.ColorContrastOnClick = 45;
            this.buttonMenu.ColorContrastOnHover = 45;
            this.buttonMenu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.buttonMenu.CustomizableEdges = borderEdges9;
            this.buttonMenu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonMenu.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonMenu.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonMenu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonMenu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonMenu.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonMenu.ForeColor = System.Drawing.Color.White;
            this.buttonMenu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonMenu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonMenu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonMenu.IconMarginLeft = 11;
            this.buttonMenu.IconPadding = 10;
            this.buttonMenu.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonMenu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonMenu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonMenu.IconSize = 25;
            this.buttonMenu.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonMenu.IdleBorderRadius = 35;
            this.buttonMenu.IdleBorderThickness = 1;
            this.buttonMenu.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonMenu.IdleIconLeftImage = null;
            this.buttonMenu.IdleIconRightImage = null;
            this.buttonMenu.IndicateFocus = false;
            this.buttonMenu.Location = new System.Drawing.Point(-40, 262);
            this.buttonMenu.Name = "buttonMenu";
            this.buttonMenu.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonMenu.OnDisabledState.BorderRadius = 35;
            this.buttonMenu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonMenu.OnDisabledState.BorderThickness = 1;
            this.buttonMenu.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonMenu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonMenu.OnDisabledState.IconLeftImage = null;
            this.buttonMenu.OnDisabledState.IconRightImage = null;
            this.buttonMenu.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonMenu.onHoverState.BorderRadius = 35;
            this.buttonMenu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonMenu.onHoverState.BorderThickness = 1;
            this.buttonMenu.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonMenu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonMenu.onHoverState.IconLeftImage = null;
            this.buttonMenu.onHoverState.IconRightImage = null;
            this.buttonMenu.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonMenu.OnIdleState.BorderRadius = 35;
            this.buttonMenu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonMenu.OnIdleState.BorderThickness = 1;
            this.buttonMenu.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonMenu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonMenu.OnIdleState.IconLeftImage = null;
            this.buttonMenu.OnIdleState.IconRightImage = null;
            this.buttonMenu.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.buttonMenu.OnPressedState.BorderRadius = 35;
            this.buttonMenu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonMenu.OnPressedState.BorderThickness = 1;
            this.buttonMenu.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonMenu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonMenu.OnPressedState.IconLeftImage = null;
            this.buttonMenu.OnPressedState.IconRightImage = null;
            this.buttonMenu.Size = new System.Drawing.Size(163, 39);
            this.buttonMenu.TabIndex = 11;
            this.buttonMenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonMenu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonMenu.TextMarginLeft = 0;
            this.buttonMenu.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.buttonMenu.UseDefaultRadiusAndThickness = true;
            this.buttonMenu.Click += new System.EventHandler(this.buttonMenu_Click_1);
            // 
            // buttonHome
            // 
            this.buttonHome.AllowAnimations = true;
            this.buttonHome.AllowMouseEffects = true;
            this.buttonHome.AllowToggling = false;
            this.buttonHome.AnimationSpeed = 200;
            this.buttonHome.AutoGenerateColors = false;
            this.buttonHome.AutoRoundBorders = false;
            this.buttonHome.AutoSizeLeftIcon = true;
            this.buttonHome.AutoSizeRightIcon = true;
            this.buttonHome.BackColor = System.Drawing.Color.Transparent;
            this.buttonHome.BackColor1 = System.Drawing.Color.Transparent;
            this.buttonHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonHome.BackgroundImage")));
            this.buttonHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHome.ButtonText = "Home";
            this.buttonHome.ButtonTextMarginLeft = 0;
            this.buttonHome.ColorContrastOnClick = 45;
            this.buttonHome.ColorContrastOnHover = 45;
            this.buttonHome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.buttonHome.CustomizableEdges = borderEdges10;
            this.buttonHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonHome.DisabledBorderColor = System.Drawing.Color.Red;
            this.buttonHome.DisabledFillColor = System.Drawing.Color.Red;
            this.buttonHome.DisabledForecolor = System.Drawing.Color.White;
            this.buttonHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonHome.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonHome.ForeColor = System.Drawing.Color.White;
            this.buttonHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonHome.IconMarginLeft = 11;
            this.buttonHome.IconPadding = 10;
            this.buttonHome.IconRightAlign = System.Drawing.ContentAlignment.TopCenter;
            this.buttonHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonHome.IconSize = 25;
            this.buttonHome.IdleBorderColor = System.Drawing.Color.Transparent;
            this.buttonHome.IdleBorderRadius = 35;
            this.buttonHome.IdleBorderThickness = 1;
            this.buttonHome.IdleFillColor = System.Drawing.Color.Transparent;
            this.buttonHome.IdleIconLeftImage = null;
            this.buttonHome.IdleIconRightImage = null;
            this.buttonHome.IndicateFocus = false;
            this.buttonHome.Location = new System.Drawing.Point(-41, 172);
            this.buttonHome.Name = "buttonHome";
            this.buttonHome.OnDisabledState.BorderColor = System.Drawing.Color.Red;
            this.buttonHome.OnDisabledState.BorderRadius = 35;
            this.buttonHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHome.OnDisabledState.BorderThickness = 1;
            this.buttonHome.OnDisabledState.FillColor = System.Drawing.Color.Red;
            this.buttonHome.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.buttonHome.OnDisabledState.IconLeftImage = null;
            this.buttonHome.OnDisabledState.IconRightImage = null;
            this.buttonHome.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.buttonHome.onHoverState.BorderRadius = 35;
            this.buttonHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHome.onHoverState.BorderThickness = 1;
            this.buttonHome.onHoverState.FillColor = System.Drawing.Color.Red;
            this.buttonHome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonHome.onHoverState.IconLeftImage = null;
            this.buttonHome.onHoverState.IconRightImage = null;
            this.buttonHome.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.buttonHome.OnIdleState.BorderRadius = 35;
            this.buttonHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHome.OnIdleState.BorderThickness = 1;
            this.buttonHome.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.buttonHome.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonHome.OnIdleState.IconLeftImage = null;
            this.buttonHome.OnIdleState.IconRightImage = null;
            this.buttonHome.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.buttonHome.OnPressedState.BorderRadius = 35;
            this.buttonHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonHome.OnPressedState.BorderThickness = 1;
            this.buttonHome.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.buttonHome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonHome.OnPressedState.IconLeftImage = null;
            this.buttonHome.OnPressedState.IconRightImage = null;
            this.buttonHome.Size = new System.Drawing.Size(164, 39);
            this.buttonHome.TabIndex = 10;
            this.buttonHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonHome.TextMarginLeft = 0;
            this.buttonHome.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.buttonHome.UseDefaultRadiusAndThickness = true;
            this.buttonHome.Click += new System.EventHandler(this.buttonHome_Click);
            // 
            // PnlImage
            // 
            this.PnlImage.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.PnlImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PnlImage.BackgroundImage")));
            this.PnlImage.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PnlImage.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.PnlImage.BorderRadius = 0;
            this.PnlImage.BorderThickness = 0;
            this.PnlImage.Controls.Add(this.pictureBox1);
            this.PnlImage.Dock = System.Windows.Forms.DockStyle.Top;
            this.PnlImage.Location = new System.Drawing.Point(0, 0);
            this.PnlImage.Name = "PnlImage";
            this.PnlImage.ShowBorders = false;
            this.PnlImage.Size = new System.Drawing.Size(200, 125);
            this.PnlImage.TabIndex = 4;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(66)))));
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.pictureBox1.Image = global::app.Properties.Resources.red_White_logo;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(200, 136);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuPnel3
            // 
            this.bunifuPnel3.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPnel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPnel3.BackgroundImage")));
            this.bunifuPnel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPnel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPnel3.BorderRadius = 3;
            this.bunifuPnel3.BorderThickness = 1;
            this.bunifuPnel3.Location = new System.Drawing.Point(200, 83);
            this.bunifuPnel3.Name = "bunifuPnel3";
            this.bunifuPnel3.ShowBorders = true;
            this.bunifuPnel3.Size = new System.Drawing.Size(1188, 605);
            this.bunifuPnel3.TabIndex = 0;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(200, 100);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.DimGray;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.DimGray;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(1208, 597);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 2;
            // 
            // lblTitle1
            // 
            this.lblTitle1.AutoSize = true;
            this.lblTitle1.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle1.Font = new System.Drawing.Font("Nirmala UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle1.ForeColor = System.Drawing.Color.White;
            this.lblTitle1.Location = new System.Drawing.Point(3, 128);
            this.lblTitle1.Name = "lblTitle1";
            this.lblTitle1.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lblTitle1.Size = new System.Drawing.Size(196, 41);
            this.lblTitle1.TabIndex = 0;
            this.lblTitle1.Text = "Cusine Craft";
            this.lblTitle1.Click += new System.EventHandler(this.label1_Click);
            // 
            // main
            // 
            this.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.ClientSize = new System.Drawing.Size(1281, 650);
            this.Controls.Add(this.PnlTop);
            this.Controls.Add(this.PnlFormLoader);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.main_Load);
            this.PnlTop.ResumeLayout(false);
            this.PnlTop.PerformLayout();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.PnlImage.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.ComponentModel.BackgroundWorker backgroundWorker1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuColorTransition bunifuColorTransition1;
        private System.Windows.Forms.Label lblTitle1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuPanel PnlFormLoader;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPnel3;
        private Bunifu.UI.WinForms.BunifuPanel PnlImage;
        private Bunifu.UI.WinForms.BunifuPanel PnlTop;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Label lblTitle2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonAbout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonCRM;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonHR;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonFR;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonInv;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonTables;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonOrders;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonMenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonHome;
    }
}

